grpc:
  url: "localhost:8070"
http:
  url: "localhost:8080"
log:
  level: debug
  environment: dev
db:
  data: '
[
    {
        "region": "europe-west",
        "cpuSingle": 1000,
        "cpuMulti": 2,
        "ram": 4096,
        "diskSpeed": 0,
        "diskSize": 40000,
        "netSpeed": 50,
        "minerRating": 1
    },
    {
        "region": "northamerica-east",
        "cpuSingle": 1000,
        "cpuMulti": 1,
        "ram": 4096,
        "diskSpeed": 0,
        "diskSize": 40000,
        "netSpeed": 50,
        "minerRating": 2
    }
]'